name: WA Bot CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "wa-bot/**"
    # For production deployment using semantic versioning
    tags:
      - "wa-bot-v*.*.*"
  pull_request:
    branches:
      - main
    paths:
      - "wa-bot/**"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker Tags
        id: docker_meta
        run: |
          # Image base name for the Docker image
          IMAGE_BASE="ghcr.io/farrelghozy/wani-wa-bot"

          # Cek trigger event
          # kalau push ke tag, ambil versi dari tag
          # kalau push biasa ke main, pake commit SHA
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/wa-bot-v//')
            echo "tags=${IMAGE_BASE}:${VERSION}, ${IMAGE_BASE}:latest" >> $GITHUB_OUTPUT
          else
            # Kalau push biasa ke main, tag-nya pake commit SHA ama latest
            echo "tags=${IMAGE_BASE}:${{ github.sha }}, ${IMAGE_BASE}:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./wa-bot
          file: ./wa-bot/Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
